### ISSUE TITLE
COMPONENTS: Render All Teacher Views

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS.Portal#12]

**Comment by mtoncic** [comment]
Hi there :) Is there some preferred way in which we want to render these teachers? Some kind of a grid?

**Comment by hassanhabib** [comment]
@mtoncic yes a grid. we should pair on that.

**Comment by mtoncic** [comment]
That sounds great! How can we get in touch?

**Comment by mtoncic** [comment]
@hassanhabib that sounds great! How can we get in touch?

**Comment by hassanhabib** [comment]
@mtoncic do you use Whatsapp?

**Comment by mtoncic** [comment]
@hassanhabib I will contact you over Linkedin and we can exchange contacts there.

**Comment by mtoncic** [comment]
This one is resolved-> should be closed

**Comment by hassanhabib** [comment]
@mtoncic sounds good. done.
