### ISSUE TITLE
BROKERS: Get All Teachers

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS.Portal#89]
Assigned to @shivangsoni

**Comment by hassanhabib** [comment]
Very similar to implementing an interface file like this:
https://github.com/hassanhabib/OtripleS.Portal/blob/master/OtripleS.Portal.Web/Brokers/Apis/IApiBroker.Assignments.cs

And also implementing the method in here:
https://github.com/hassanhabib/OtripleS.Portal/blob/master/OtripleS.Portal.Web/Brokers/Apis/ApiBroker.Assignments.cs

**Comment by shivangsoni** [comment]
Will create brokers for dining.

**Comment by ShriHumrudha** [comment]
Completed
